web/lp_detection/lp_detection/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("main.urls")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/lp_detection/main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("train/", views.train_yolo, name="train"),
    path("model_mode/", views.send_inference_task, name="mode"),
    path("task_status/", views.update_task_status, name="update_status"),
    path("inference/", views.get_prediction, name="detection_results"),
]

web/lp_detection/main/models.py
from django.db import models
from django.utils import timezone


def current_time():
    return timezone.now().time()


class LicensePlate(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to="uploads/")
    number = models.IntegerField(null=True, blank=True)
    annotations = models.FileField(upload_to="uploads/", null=True, blank=True)

    def __str__(self):
        return self.title


class Task(models.Model):
    id = models.AutoField(primary_key=True)
    # number = models.IntegerField()
    status = models.CharField(max_length=50)
    worker_id = models.CharField(max_length=50)
    mode = models.CharField(max_length=50)
    time = models.TimeField(default=current_time)

web/lp_detection/main/forms.py
from django import forms

from .models import LicensePlate


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class ImageForm(forms.ModelForm):
    image = MultipleFileField(required=False)

    class Meta:
        model = LicensePlate
        fields = [
            "image",
        ]

web/lp_detection/main/views.py
import json
import os

import pika
from django.contrib import messages
from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import render
from main.models import LicensePlate, Task

from .forms import ImageForm

RMQ_URL = os.getenv("RMQ_URL")
QUEUE_NAME = os.environ.get("QUEUE_NAME", "test_direct")
EXCHANGE_NAME = os.environ.get("EXCHANGE_NAME", "to_direct")
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"


def index(request):
    if request.method == "POST":
        form = ImageForm(request.POST)
        files = request.FILES.getlist("image")
        if form.is_valid():
            ids = []
            for image in files:
                lp = LicensePlate.objects.create(title=image.name, image=image)
                ids.append(lp.id)
            messages.success(request, "Images added")
            return render(
                request,
                "main/index.html",
                {"form": form, "images": LicensePlate.objects.filter(id__in=ids)},
            )

        return render(request, "main/index.html", {"form": form})

    else:
        form = ImageForm()
    return render(request, "main/index.html", {"form": form})


def train_yolo(request):
    pass


def send_inference_task(request):
    try:
        recieved_data = request.GET.dict()
    except Exception as e:
        print(e)
        return render(request, "main/error.html")

    routing_key = ""
    worker_id = "Unknown"

    images = []
    for k in recieved_data.keys():
        if k == "csrfmiddlewaretoken":
            continue
        images.append(recieved_data[k])
    request.session["images"] = images

    with pika.BlockingConnection(pika.URLParameters(RMQ_URL)) as connection:
        with connection.channel() as channel:

            task = Task(status="PENDING", worker_id=worker_id, mode="inference")
            task.save()
            task_num = task.id
            data = {"images": images, "task_id": task_num}

            channel.exchange_declare(
                exchange=EXCHANGE_NAME, exchange_type="fanout", durable=True
            )
            channel.queue_declare(queue=f"{QUEUE_NAME}_rejected", durable=True)
            channel.queue_declare(
                queue=QUEUE_NAME,
                durable=True,
                arguments={
                    "x-dead-letter-exchange": "",
                    "x-dead-letter-routing-key": f"{QUEUE_NAME}_rejected",
                },
            )
            channel.queue_bind(
                queue=QUEUE_NAME, exchange=EXCHANGE_NAME, routing_key="direct_out"
            )

            channel.basic_publish(
                exchange=EXCHANGE_NAME,
                routing_key=routing_key,
                body=json.dumps(data, cls=DjangoJSONEncoder).encode(),
            )

    context = {"task_num": task_num, "mode": "inference"}

    return render(request, "main/mode.html", context)


async def update_task_status(request):
    print("[update_task_status]")
    tasks = [task async for task in Task.objects.all()]
    context = {"tasks": tasks}
    return render(request, "main/tasks.html", context)


def get_prediction(request):
    images = request.session.get("images")
    context = {"images": images}
    return render(request, "main/get_predicted.html", context)

web/lp_detection/main/templates/main/error.html
<h1>Sorry, some error occured..</h1>

web/lp_detection/main/templates/main/get_predicted.html
{% extends "main/pattern.html" %}

{% block title %}
    Detections
{% endblock %}

{% block content %}
    <h2 class="tasks_container">Image(-s) with detected license plate(-s): </h2>
    {% csrf_token %}
    {% for image in images %}
        <h3>{{ image }}</h3>
        <img src="../media/preds/out_det_{{image}}.png" alt="connect" style="max-height:300px">
    {% endfor %}
{% endblock %}

web/lp_detection/main/templates/main/index.html
{% extends "main/pattern.html" %}

{% block title %}
   Upload images
{% endblock %}

{% block content %}
    {% if form.errors %}
        <div class="alert alert-danger">
            {{ form.errors }}
        </div>
    {% endif %}

    {% if images %}

        <form class='modal' method="get" action="{% url 'main:mode' %}" style="max-width: 100%;">
            <div class="modal-body">
                <h2 class="modal-title">Succesfully uploaded:</h2>
                {% csrf_token %}
                <div class="grid">
                    {% for image in images %}
                        <h4>{{image.title}}</h4>
                        <img src="{{ image.image.url}}" alt="connect">
                        <input type="hidden" name="image{{image.id}}" value="{{image.title}}">
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="submit">Go see preds</button>
                </div>
            </div>
        </form>

    {% else %}

        <form class="modal" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="modal-body">
                <h2 class="modal-title">Upload images</h2>
                <label class="input-file">
                    {{ form.image }}
                    <span>Drag file(s) here to upload</span>
                </label>
            </div>
            <div class="modal-footer">
                <button class="btn-primary">Upload</button>
            </div>

        </form>

    {% endif %}
{% endblock %}

web/lp_detection/main/templates/main/mode.html
{% extends "main/pattern.html" %}

{% block title %}
    Model in {{mode}} mode
{% endblock %}

{% block content %}
    <h2 class="tasks_container">Model will be turned in {{mode}} mode... Task number {{task_num}}. Go to see its
        <a href="/task_status/">status</a>
    </h2>
{% endblock %}

web/lp_detection/main/templates/main/pattern.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/pattern.css' %}">
    </head>
    <body>
      <nav>
        <a href="/" class="underline">Upload</a>
        <a href="/train/" class="underline">Train</a>
        <a href="/task_status/" class="underline">See Tasks</a>
        <a href="/inference/" class="underline">Inference</a>
      </nav>

      {% block content %}
      {% endblock %}
    </body>
</html>

web/lp_detection/main/templates/main/tasks.html
{% extends "main/pattern.html" %}

{% block title %}
    Tasks
{% endblock %}

{% block content %}

    <div class="tasks_container">
        <h2>Tasks</h2>
        <ul class="responsive-table">
        <li class="table-header">
            <div class="col col-1">ID</div>
            <div class="col col-2">Status</div>
            <div class="col col-3">Worker_id</div>
            <div class="col col-4">Mode</div>
            <div class="col col-5">Created at</div>
        </li>
        {% for i in tasks %}
            <li class="table-row">
                <div class="col col-1">{{ i.id }}</div>
                <div class="col col-2">{{ i.status }}</div>
                <div class="col col-3">{{ i.worker_id }}</div>
                <div class="col col-4">{{ i.mode }}</div>
                <div class="col col-5">{{ i.time }}</div>
            </li>
        {% endfor %}
        </ul>
    </div>

{% endblock %}